function [hPanel, hSliderX, hSliderY, hSliderZ, hAxis, hPlotObj, hText] = addPanel(hFig)

nR = 3;
nC = 4;

for r = 1:nR
    y0(r, 1:nC) = 1-r/nR;
    for c = 1:nC
        x0(1:nR, c) = (c-1)/nC;
        
        % panel
        hPanel.dv(r, c) = uipanel('Parent',                    hFig,...    
                             'Title',                        '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'Position',                  [x0(r,c), y0(r,c) 1/nC 1/nR],...
                                    'visible',                      'on', ...
                                'ForegroundColor',       'white',...
                                'BackgroundColor',       'black', ...
                                'HighlightColor',          'k',...
                                'ShadowColor',            'black');

        % axis
        hAxis.ct(r,c) = axes('Parent',                   hPanel.dv(r,c), ...
                            'color',        'none',...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.1 0.1 0.8 0.8]);
        hold(hAxis.ct(r,c), 'on');
        hPlotObj.ct(r,c) = imshow([], 'parent', hAxis.ct(r,c));

         hAxis.dose(r,c) = axes('Parent',                   hPanel.dv(r,c), ...
                            'color',        'none',...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.1 0.1 0.8 0.8]);
        hold(hAxis.dose(r,c), 'on');
        hPlotObj.dose(r,c) = imshow([], 'parent', hAxis.dose(r,c));
        
        axis(hAxis.ct(r, c), 'tight', 'equal');
        axis(hAxis.dose(r, c), 'tight', 'equal');

    colormap(hAxis.dose(r,c), jet);
    hPlotObj.cb_dose(r,c) = colorbar(hAxis.dose(r,c), 'west');
    hPlotObj.cb_dose(r,c).Visible = 'off';
    hPlotObj.cb_dose(r,c).Color = 'w';
    ps = hPlotObj.cb_dose(r,c).Position;
    ps(1) = ps(1)*.5;
    hPlotObj.cb_dose(r,c).Position = ps;

    % cross lines
    hPlotObj.xLine(r,c) = line(hAxis.ct(r,c),...
    'XData', [], 'YData', [], 'Color', 'g', 'LineStyle', '-', 'LineWidth', 1/2);

    hPlotObj.yLine(r,c) = line(hAxis.ct(r,c),...
    'XData', [], 'YData', [], 'Color', 'g', 'LineStyle', '-', 'LineWidth', 1/2);


    end
    
    hText.pos(r) = text(hAxis.ct(r, 1), 0, 0.95, '',...
    'Color', 'cyan', 'FontSize', 12, 'FontWeight', 'Bold', ...   
    'Units', 'normalized', 'visible', 'off');
end
    
hText.pp = text(hAxis.dose(1, 4), 0, 0.95, '',...
    'Color', 'cyan', 'FontSize', 12, 'FontWeight', 'Bold', ...   
    'Units', 'normalized', 'visible', 'off');

for r = 1:3
 hAxis.ct(r,1).Visible = 'on';
 hAxis.ct(r,1).XAxis.Color = 'w';
 hAxis.ct(r,1).YAxis.Color = 'w';

 hAxis.dose(r,1).XAxisLocation = 'top';
 hAxis.dose(r,1).YAxisLocation = 'right';
 hAxis.dose(r,1).Visible = 'on';
 hAxis.dose(r,1).XAxis.Color = 'w';
 hAxis.dose(r,1).YAxis.Color = 'w';
end
 
 
for c = 1:4
    hAxis.ct(3,c).YDir = 'normal';
    hAxis.ct(2,c).XDir = 'reverse';
    hAxis.ct(2,c).YDir = 'normal';

    hAxis.dose(3,c).YDir = 'normal';
    hAxis.dose(2,c).XDir = 'reverse';
    hAxis.dose(2,c).YDir = 'normal';
end

%% Slider
for r = 1:3
    hPanel.slider(r) = uipanel('Parent',                    hFig,...  
                            'FontSize',                 12,...
                            'Units',                     'normalized', ...
                            'Position',                  [0.98 1-r/3 0.02 1/3],...
                            'visible',                      'on', ...
                            'ForegroundColor',       'white',...
                            'BackgroundColor',       'black', ...
                            'HighlightColor',        'black',...
                            'ShadowColor',            'black');
end

hSliderZ = uicontrol('Parent',  hPanel.slider(1),...
            'Style','slider','units', 'normalized',...
            'Position',[0. 0.1 0.95 0.8],...
            'BackgroundColor', 'b',...
            'ForegroundColor', 'w',...
                'Callback', @hSlider_CTz_Callback);

hSliderX = uicontrol('Parent',  hPanel.slider(2),...
            'Style','slider','units', 'normalized',...
            'Position',[0. 0.1 0.95 0.8],...
            'BackgroundColor', 'r',...
            'ForegroundColor', 'w',...
                'Callback', @hSlider_CTx_Callback);
hSliderY = uicontrol('Parent',  hPanel.slider(3),...
            'Style','slider','units', 'normalized',...
            'Position',[0. 0.1 0.95 0.8],...
            'BackgroundColor', 'g',...
            'ForegroundColor', 'w',...
                'Callback', @hSlider_CTy_Callback);
            
set(hSliderX, 'Min', 1, 'Max', 100, 'SliderStep', [1 5]./100, 'Value', 1);
set(hSliderY, 'Min', 1, 'Max', 100, 'SliderStep', [1 5]./100, 'Value', 1);
set(hSliderZ, 'Min', 1, 'Max', 100, 'SliderStep', [1 5]./100, 'Value', 1);
for r = 1:3
    uistack(hPanel.slider(r), 'top');
end